[tool.poetry]
name = "src"
version = "0.1.0"
description = "Econ narrative utilities"
authors = ["Mourad Heddaya <mourad@uchicago.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
